In [1]:
#1.fill null values of a  data frame using median and mode
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,np.nan,65.26,110.5,948.5,np.nan,5760,1983.43,np.nan,250.45, 75.29,3045.6],
'sale_amt':[10.5,20.65,np.nan,11.5,98.5,np.nan,57,19.43,np.nan,25.45, 75.29,35.6]})
print(df)

     ord_no  purch_amt  sale_amt
0   70001.0     150.50     10.50
1       NaN        NaN     20.65
2   70002.0      65.26       NaN
3   70004.0     110.50     11.50
4       NaN     948.50     98.50
5   70005.0        NaN       NaN
6       NaN    5760.00     57.00
7   70010.0    1983.43     19.43
8   70003.0        NaN       NaN
9   70012.0     250.45     25.45
10      NaN      75.29     75.29
11  70013.0    3045.60     35.60


In [2]:
df['purch_amt'].fillna(df['purch_amt'].median(), inplace=True)
print(df)

     ord_no  purch_amt  sale_amt
0   70001.0     150.50     10.50
1       NaN     250.45     20.65
2   70002.0      65.26       NaN
3   70004.0     110.50     11.50
4       NaN     948.50     98.50
5   70005.0     250.45       NaN
6       NaN    5760.00     57.00
7   70010.0    1983.43     19.43
8   70003.0     250.45       NaN
9   70012.0     250.45     25.45
10      NaN      75.29     75.29
11  70013.0    3045.60     35.60


In [ ]:
#2.what is the difference between merging and joining in dataframe

Both join and merge can be used to combines two dataframes but the join method combines two dataframes on the basis of their indexes whereas the merge method is more versatile and allows us to specify columns beside the index to join on for both dataframes.
Merge:=
    The pd. merge() function recognizes that each DataFrame has an "employee" column, and automatically joins using this column as a key. The result of the merge is a new DataFrame that combines the information from the two inputs.
Join:=
    Join columns with other DataFrame either on index or on a key column. Efficiently join multiple DataFrame objects by index at once by passing a list.

In [3]:
#3.create a numpy array and a dataframe and concatenate them
array = np.arange(9)
print(array)
array1 = array.reshape((3,3))
print(array1)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
array2 = np.arange(10,19).reshape(3,3)
array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
np.concatenate((array1, array2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
#4.create a data frame and add a column. add names in it and use apply function to return names whose length is greater than 5 
data = {
     'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
              'Manchester', 'Cairo', 'Osaka'],

}
row_labels = [101, 102, 103, 104, 105, 106, 107]
data

{'city': ['Mexico City',
  'Toronto',
  'Prague',
  'Shanghai',
  'Manchester',
  'Cairo',
  'Osaka']}

In [7]:
df = pd.DataFrame(data=data, index=row_labels)
df

city
101  Mexico City
102      Toronto
103       Prague
104     Shanghai
105   Manchester
106        Cairo
107        Osaka

In [8]:
df.city

101    Mexico City
102        Toronto
103         Prague
104       Shanghai
105     Manchester
106          Cairo
107          Osaka
Name: city, dtype: object

In [9]:
df['Length']=df['city'].str.len()
print(df)

            city  Length
101  Mexico City      11
102      Toronto       7
103       Prague       6
104     Shanghai       8
105   Manchester      10
106        Cairo       5
107        Osaka       5


In [10]:
df[df["Length"]>5]

city  Length
101  Mexico City      11
102      Toronto       7
103       Prague       6
104     Shanghai       8
105   Manchester      10